BEGIN TRANSACTION

CREATE TABLE BAGUVIX.BI_TIEMPO (
	id_tiempo DECIMAL(18,0) PRIMARY KEY,
	mes DECIMAL(18,0),
	anio DECIMAL(18,0)
)

CREATE TABLE BAGUVIX.BI_CLIENTE (
	id_cliente DECIMAL(18,0) PRIMARY KEY,
	edad NVARCHAR(255),
	sexo NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_SUCURSAL (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	MAIL NVARCHAR(255),
	DIRECCION NVARCHAR(255),
	CIUDAD NVARCHAR(255),
	TELEFONO DECIMAL(18,0)
)

CREATE TABLE BAGUVIX.BI_MODELO (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	NOMBRE NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_FABRICANTE (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	NOMBRE NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_TIPO_AUTO (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_TIPO_CAJA_CAMBIOS (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_TIPO_MOTOR (
	CODIGO DECIMAL(18,0) PRIMARY KEY
)

CREATE TABLE BAGUVIX.BI_TIPO_TRANSMISION (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_POTENCIA (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	NIVEL NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_AUTOPARTES (
	CODIGO DECIMAL(18,0) PRIMARY KEY,
	DESCRIPCION NVARCHAR(255)
)

CREATE TABLE BAGUVIX.BI_VENTAS_AUTOMOVILES (
	ID_TIEMPO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIEMPO(ID_TIEMPO),
	ID_CLIENTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_CLIENTE(ID_CLIENTE),
	ID_SUCURSAL DECIMAL(18,0) REFERENCES BAGUVIX.BI_SUCURSAL(CODIGO),
	ID_MODELO DECIMAL(18,0) REFERENCES BAGUVIX.BI_MODELO(CODIGO),
	ID_FABRICANTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_FABRICANTE(CODIGO),
	ID_TIPO_AUTO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_AUTO(CODIGO),
	ID_TIPO_CAJA DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_CAJA_CAMBIOS(CODIGO),
	ID_TIPO_MOTOR DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_MOTOR(CODIGO),
	ID_TIPO_TRANSMISION DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_TRANSMISION(CODIGO),
	ID_POTENCIA DECIMAL(18,0) REFERENCES BAGUVIX.BI_POTENCIA(CODIGO),
	unidades DECIMAL(18,0),
	precio NUMERIC(19, 4),
	dias_en_stock DECIMAL(18,0),
	PRIMARY KEY(ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA)
)

CREATE TABLE BAGUVIX.BI_COMPRAS_AUTOMOVILES (
	ID_TIEMPO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIEMPO(ID_TIEMPO),
	ID_CLIENTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_CLIENTE(ID_CLIENTE),
	ID_SUCURSAL DECIMAL(18,0) REFERENCES BAGUVIX.BI_SUCURSAL(CODIGO),
	ID_MODELO DECIMAL(18,0) REFERENCES BAGUVIX.BI_MODELO(CODIGO),
	ID_FABRICANTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_FABRICANTE(CODIGO),
	ID_TIPO_AUTO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_AUTO(CODIGO),
	ID_TIPO_CAJA DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_CAJA_CAMBIOS(CODIGO),
	ID_TIPO_MOTOR DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_MOTOR(CODIGO),
	ID_TIPO_TRANSMISION DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_TRANSMISION(CODIGO),
	ID_POTENCIA DECIMAL(18,0) REFERENCES BAGUVIX.BI_POTENCIA(CODIGO),
	unidades DECIMAL(18,0),
	precio NUMERIC(19, 4),
	PRIMARY KEY(ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA)
)

CREATE TABLE BAGUVIX.BI_VENTAS_AUTOPARTES (
	ID_TIEMPO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIEMPO(ID_TIEMPO),
	ID_CLIENTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_CLIENTE(ID_CLIENTE),
	ID_SUCURSAL DECIMAL(18,0) REFERENCES BAGUVIX.BI_SUCURSAL(CODIGO),
	ID_MODELO DECIMAL(18,0) REFERENCES BAGUVIX.BI_MODELO(CODIGO),
	ID_FABRICANTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_FABRICANTE(CODIGO),
	ID_TIPO_AUTO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_AUTO(CODIGO),
	ID_TIPO_CAJA DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_CAJA_CAMBIOS(CODIGO),
	ID_TIPO_MOTOR DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_MOTOR(CODIGO),
	ID_TIPO_TRANSMISION DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_TRANSMISION(CODIGO),
	ID_POTENCIA DECIMAL(18,0) REFERENCES BAGUVIX.BI_POTENCIA(CODIGO),
	ID_AUTOPARTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_AUTOPARTES(CODIGO),
	unidades DECIMAL(18,0),
	precio NUMERIC(19, 4),
	PRIMARY KEY(ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, ID_AUTOPARTE)
)

CREATE TABLE BAGUVIX.BI_COMPRAS_AUTOPARTES (
	ID_TIEMPO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIEMPO(ID_TIEMPO),
	ID_CLIENTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_CLIENTE(ID_CLIENTE),
	ID_SUCURSAL DECIMAL(18,0) REFERENCES BAGUVIX.BI_SUCURSAL(CODIGO),
	ID_MODELO DECIMAL(18,0) REFERENCES BAGUVIX.BI_MODELO(CODIGO),
	ID_FABRICANTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_FABRICANTE(CODIGO),
	ID_TIPO_AUTO DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_AUTO(CODIGO),
	ID_TIPO_CAJA DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_CAJA_CAMBIOS(CODIGO),
	ID_TIPO_MOTOR DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_MOTOR(CODIGO),
	ID_TIPO_TRANSMISION DECIMAL(18,0) REFERENCES BAGUVIX.BI_TIPO_TRANSMISION(CODIGO),
	ID_POTENCIA DECIMAL(18,0) REFERENCES BAGUVIX.BI_POTENCIA(CODIGO),
	ID_AUTOPARTE DECIMAL(18,0) REFERENCES BAGUVIX.BI_AUTOPARTES(CODIGO),
	unidades DECIMAL(18,0),
	precio NUMERIC(19, 4),
	PRIMARY KEY(ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, ID_AUTOPARTE)
)

declare @fi datetime, @ff datetime
set @fi = (select min(fecha) from BAGUVIX.TRANSACCION)
Set @ff = (select max(fecha) from BAGUVIX.TRANSACCION)
 
while (YEAR(@fi) != YEAR(@ff) OR MONTH(@fi) != MONTH(@ff))
begin
insert into BAGUVIX.BI_TIEMPO (id_tiempo, Anio, Mes)
select year(@fi)*100+month(@fi) as TimeId,
year(@fi) as anio,
month(@fi) as Mes
set @fi = DATEADD(month, 1, @fi)
end


INSERT INTO BAGUVIX.BI_CLIENTE (id_cliente, edad, sexo)
VALUES 
(1, '18 - 30 años', 'M'), 
(2, '18 - 30 años', 'F'),
(3, '18 - 30 años', NULL),
(4, '31 – 50 años', 'M'),
(5, '31 – 50 años', 'F'),
(6, '31 – 50 años', NULL),
(7, '> 50 años', 'M'),
(8, '> 50 años', 'F'),
(9, '> 50 años', NULL);

INSERT INTO BAGUVIX.BI_SUCURSAL
SELECT * FROM BAGUVIX.SUCURSAL;

INSERT INTO BAGUVIX.BI_MODELO
SELECT m.CODIGO, m.NOMBRE FROM BAGUVIX.MODELO m;

INSERT INTO BAGUVIX.BI_FABRICANTE
SELECT * FROM BAGUVIX.FABRICANTE;

INSERT INTO BAGUVIX.BI_TIPO_AUTO
SELECT * FROM BAGUVIX.TIPO_AUTO;

INSERT INTO BAGUVIX.BI_TIPO_CAJA_CAMBIOS
SELECT * FROM BAGUVIX.TIPO_CAJA;

INSERT INTO BAGUVIX.BI_TIPO_MOTOR
SELECT * FROM BAGUVIX.TIPO_MOTOR;

INSERT INTO BAGUVIX.BI_TIPO_TRANSMISION
SELECT * FROM BAGUVIX.TIPO_TRANSMISION;

INSERT INTO BAGUVIX.BI_POTENCIA (CODIGO, NIVEL)
VALUES
(1, '50-150cv'),
(2, '151-300cv'),
(3, '> 300cv');

INSERT INTO BAGUVIX.BI_AUTOPARTES (CODIGO, DESCRIPCION)
select CODIGO, DESCRIPCION from BAGUVIX.AUTOPARTE

INSERT INTO BAGUVIX.BI_VENTAS_AUTOMOVILES (ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, UNIDADES, PRECIO, DIAS_EN_STOCK)
SELECT 
BT.id_tiempo,
BC.ID_CLIENTE,
S.CODIGO,
A.MODELO,
A.FABRICANTE,
M.TIPO,
M.CAJA,
M.MOTOR,
M.TRANSMISION, 
BP.CODIGO,
COUNT(T.NUMERO),
SUM(TA.PRECIO),
SUM(COALESCE( DATEDIFF(day, TC.FECHA, T.FECHA) ,0))
FROM BAGUVIX.TRANSACCION_AUTOMOVIL TA
INNER JOIN BAGUVIX.TRANSACCION T
ON T.NUMERO = TA.TRANSACCION
INNER JOIN BAGUVIX.BI_TIEMPO BT
ON BT.anio = YEAR(T.FECHA) and BT.mes = MONTH(T.FECHA)
INNER JOIN BAGUVIX.CLIENTE C
ON T.CLIENTE = C.CODIGO
INNER JOIN BAGUVIX.BI_CLIENTE BC
ON 
CASE 
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 31
THEN '18 - 30 años'
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 51
THEN '31 – 50 años'
ELSE 
'> 50 años'
END = BC.edad 
AND BC.SEXO IS NULL
INNER JOIN BAGUVIX.SUCURSAL S 
ON T.SUCURSAL = S.CODIGO
INNER JOIN BAGUVIX.AUTO A
ON A.PATENTE = TA.AUTO
INNER JOIN BAGUVIX.MODELO M
ON A.MODELO = M.CODIGO
INNER JOIN BAGUVIX.BI_POTENCIA BP
ON
CASE 
WHEN M.POTENCIA < 151
THEN '50-150cv'
WHEN M.POTENCIA < 301
THEN '151-300cv'
ELSE 
'> 300cv'
END = BP.NIVEL 
INNER JOIN BAGUVIX.TRANSACCION_AUTOMOVIL TAC
ON TAC.AUTO = TA.AUTO AND TAC.TRANSACCION != TA.TRANSACCION
INNER JOIN BAGUVIX.TRANSACCION TC
ON TC.NUMERO = TAC.TRANSACCION AND TC.TIPO_TRANSACCION = 'COMPRA'
WHERE T.TIPO_TRANSACCION = 'VENTA'
GROUP BY BT.id_tiempo, BC.ID_CLIENTE, S.CODIGO, A.MODELO, A.FABRICANTE, M.TIPO, M.CAJA, M.MOTOR, M.TRANSMISION, BP.CODIGO;


INSERT INTO BAGUVIX.BI_COMPRAS_AUTOMOVILES (ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, UNIDADES, PRECIO)
SELECT 
BT.id_tiempo,
BC.ID_CLIENTE,
S.CODIGO,
A.MODELO,
A.FABRICANTE,
M.TIPO,
M.CAJA,
M.MOTOR,
M.TRANSMISION, 
BP.CODIGO,
COUNT(T.NUMERO),
SUM(TA.PRECIO)
FROM BAGUVIX.TRANSACCION_AUTOMOVIL TA
INNER JOIN BAGUVIX.TRANSACCION T
ON T.NUMERO = TA.TRANSACCION
INNER JOIN BAGUVIX.BI_TIEMPO BT
ON BT.anio = YEAR(T.FECHA) and BT.mes = MONTH(T.FECHA)
INNER JOIN BAGUVIX.CLIENTE C
ON T.CLIENTE = C.CODIGO
INNER JOIN BAGUVIX.BI_CLIENTE BC
ON 
CASE 
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 31
THEN '18 - 30 años'
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 51
THEN '31 – 50 años'
ELSE 
'> 50 años'
END = BC.edad 
AND BC.SEXO IS NULL
INNER JOIN BAGUVIX.SUCURSAL S 
ON T.SUCURSAL = S.CODIGO
INNER JOIN BAGUVIX.AUTO A
ON A.PATENTE = TA.AUTO
INNER JOIN BAGUVIX.MODELO M
ON A.MODELO = M.CODIGO
INNER JOIN BAGUVIX.BI_POTENCIA BP
ON
CASE 
WHEN M.POTENCIA < 151
THEN '50-150cv'
WHEN M.POTENCIA < 301
THEN '151-300cv'
ELSE 
'> 300cv'
END = BP.NIVEL 
WHERE T.TIPO_TRANSACCION = 'COMPRA'
GROUP BY BT.id_tiempo, BC.ID_CLIENTE, S.CODIGO, A.MODELO, A.FABRICANTE, M.TIPO, M.CAJA, M.MOTOR, M.TRANSMISION, BP.CODIGO;

INSERT INTO BAGUVIX.BI_VENTAS_AUTOPARTES (ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, ID_AUTOPARTE, UNIDADES, PRECIO)
SELECT 
BT.id_tiempo,
BC.ID_CLIENTE,
S.CODIGO,
A.MODELO,
A.FABRICANTE,
M.TIPO,
M.CAJA,
M.MOTOR,
M.TRANSMISION, 
BP.CODIGO,
A.CODIGO,
SUM(TA.CANTIDAD),
SUM(TA.PRECIO * TA.CANTIDAD)
FROM BAGUVIX.TRANSACCION_AUTOPARTE TA
INNER JOIN BAGUVIX.TRANSACCION T
ON T.NUMERO = TA.TRANSACCION
INNER JOIN BAGUVIX.BI_TIEMPO BT
ON BT.anio = YEAR(T.FECHA) and BT.mes = MONTH(T.FECHA)
INNER JOIN BAGUVIX.CLIENTE C
ON T.CLIENTE = C.CODIGO
INNER JOIN BAGUVIX.BI_CLIENTE BC
ON 
CASE 
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 31
THEN '18 - 30 años'
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 51
THEN '31 – 50 años'
ELSE 
'> 50 años'
END = BC.edad 
AND BC.SEXO IS NULL
INNER JOIN BAGUVIX.SUCURSAL S 
ON T.SUCURSAL = S.CODIGO
INNER JOIN BAGUVIX.AUTOPARTE A
ON A.CODIGO = TA.AUTOPARTE
INNER JOIN BAGUVIX.MODELO M
ON A.MODELO = M.CODIGO
INNER JOIN BAGUVIX.BI_POTENCIA BP
ON
CASE 
WHEN M.POTENCIA < 151
THEN '50-150cv'
WHEN M.POTENCIA < 301
THEN '151-300cv'
ELSE 
'> 300cv'
END = BP.NIVEL 
WHERE T.TIPO_TRANSACCION = 'VENTA'
GROUP BY BT.id_tiempo, BC.ID_CLIENTE, S.CODIGO, A.MODELO, A.FABRICANTE, M.TIPO, M.CAJA, M.MOTOR, M.TRANSMISION, BP.CODIGO, A.CODIGO;


INSERT INTO BAGUVIX.BI_COMPRAS_AUTOPARTES (ID_TIEMPO, ID_CLIENTE, ID_SUCURSAL, ID_MODELO, ID_FABRICANTE, ID_TIPO_AUTO, ID_TIPO_CAJA, ID_TIPO_MOTOR, ID_TIPO_TRANSMISION, ID_POTENCIA, ID_AUTOPARTE, UNIDADES, PRECIO)
SELECT 
BT.id_tiempo,
BC.ID_CLIENTE,
S.CODIGO,
A.MODELO,
A.FABRICANTE,
M.TIPO,
M.CAJA,
M.MOTOR,
M.TRANSMISION, 
BP.CODIGO,
A.CODIGO,
SUM(TA.CANTIDAD),
SUM(TA.PRECIO * TA.CANTIDAD)
FROM BAGUVIX.TRANSACCION_AUTOPARTE TA
INNER JOIN BAGUVIX.TRANSACCION T
ON T.NUMERO = TA.TRANSACCION
INNER JOIN BAGUVIX.BI_TIEMPO BT
ON BT.anio = YEAR(T.FECHA) and BT.mes = MONTH(T.FECHA)
INNER JOIN BAGUVIX.CLIENTE C
ON T.CLIENTE = C.CODIGO
INNER JOIN BAGUVIX.BI_CLIENTE BC
ON 
CASE 
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 31
THEN '18 - 30 años'
WHEN DATEDIFF(YY, C.FECHA_NACIMIENTO, GETDATE()) < 51
THEN '31 – 50 años'
ELSE 
'> 50 años'
END = BC.edad 
AND BC.SEXO IS NULL
INNER JOIN BAGUVIX.SUCURSAL S 
ON T.SUCURSAL = S.CODIGO
INNER JOIN BAGUVIX.AUTOPARTE A
ON A.CODIGO = TA.AUTOPARTE
INNER JOIN BAGUVIX.MODELO M
ON A.MODELO = M.CODIGO
INNER JOIN BAGUVIX.BI_POTENCIA BP
ON
CASE 
WHEN M.POTENCIA < 151
THEN '50-150cv'
WHEN M.POTENCIA < 301
THEN '151-300cv'
ELSE 
'> 300cv'
END = BP.NIVEL 
WHERE T.TIPO_TRANSACCION = 'COMPRA'
GROUP BY BT.id_tiempo, BC.ID_CLIENTE, S.CODIGO, A.MODELO, A.FABRICANTE, M.TIPO, M.CAJA, M.MOTOR, M.TRANSMISION, BP.CODIGO, A.CODIGO;

GO 

CREATE VIEW BAGUVIX.BI_CANTIDAD_AUTOS_VENDIDOS_COMPRADOS 
AS
SELECT 
T.anio AS AÑO,
T.MES, 
S.CODIGO AS "CODIGO DE SUCURSAL" , 
S.MAIL AS "MAIL DE SUCURSAL",
(SELECT COALESCE(SUM(VA.UNIDADES), 0) FROM BAGUVIX.BI_VENTAS_AUTOMOVILES VA WHERE VA.ID_SUCURSAL = S.CODIGO AND VA.ID_TIEMPO = T.ID_TIEMPO) AS "VENTAS AUTOMOVILES",
(SELECT COALESCE(SUM(CA.UNIDADES), 0) FROM BAGUVIX.BI_COMPRAS_AUTOMOVILES CA WHERE CA.ID_SUCURSAL = S.CODIGO AND CA.ID_TIEMPO = T.ID_TIEMPO) AS "COMPRAS AUTOMOVILES"
FROM BAGUVIX.BI_TIEMPO T, BAGUVIX.BI_SUCURSAL S 
GROUP BY T.mes, T.anio, T.id_tiempo, S.MAIL, S.CODIGO
GO

CREATE VIEW BAGUVIX.BI_PRECIO_PROMEDIO_AUTOMOVILES 
AS
SELECT COALESCE(SUM(VA.PRECIO), 0)/COALESCE(SUM(VA.UNIDADES), 1) AS "PRECIO PROMEDIO VENTAS AUTOMOVILES",
(SELECT COALESCE(SUM(CA.PRECIO), 0)/COALESCE(SUM(CA.UNIDADES), 1) FROM BAGUVIX.BI_COMPRAS_AUTOMOVILES CA) AS "PRECIO PROMEDIO COMPRAS AUTOMOVILES"
FROM BAGUVIX.BI_VENTAS_AUTOMOVILES VA
GO

CREATE VIEW BAGUVIX.BI_GANANCIAS_AUTOMOVILES
AS
SELECT 
T.anio AS AÑO,
T.MES, 
S.CODIGO AS "CODIGO DE SUCURSAL" , 
S.MAIL AS "MAIL DE SUCURSAL",
(SELECT COALESCE(SUM(VA.PRECIO), 0) FROM BAGUVIX.BI_VENTAS_AUTOMOVILES VA WHERE VA.ID_SUCURSAL = S.CODIGO AND VA.ID_TIEMPO = T.ID_TIEMPO) - (SELECT COALESCE(SUM(CA.PRECIO), 0) FROM BAGUVIX.BI_COMPRAS_AUTOMOVILES CA WHERE CA.ID_SUCURSAL = S.CODIGO AND CA.ID_TIEMPO = T.ID_TIEMPO) AS "GANANCIAS"
FROM BAGUVIX.BI_TIEMPO T, BAGUVIX.BI_SUCURSAL S 
GROUP BY T.mes, T.anio, T.id_tiempo, S.MAIL, S.CODIGO
GO


CREATE VIEW BAGUVIX.BI_TIEMPO_STOCK_PROMEDIO_AUTOS_POR_MODELO
AS
SELECT 
M.CODIGO as "CODIGO MODELO", 
M.NOMBRE as "NOMBRE MODELO",
SUM(VA.dias_en_stock) / COALESCE(SUM(VA.unidades), 1) as tiempo_stock_promedio
FROM BAGUVIX.BI_VENTAS_AUTOMOVILES VA
INNER JOIN BAGUVIX.MODELO M
on M.CODIGO = VA.ID_MODELO
GROUP BY VA.ID_MODELO, M.CODIGO, M.NOMBRE
GO

CREATE VIEW BAGUVIX.BI_PRECIO_PROMEDIO_AUTOPARTE 
AS
SELECT 
A.DESCRIPCION as "NOMBRE AUTOPARTE",
(SELECT COALESCE(SUM(VA.PRECIO), 0)/COALESCE(SUM(VA.UNIDADES), 1) FROM BAGUVIX.BI_VENTAS_AUTOPARTES VA WHERE VA.ID_AUTOPARTE = A.CODIGO) AS "PRECIO PROMEDIO VENTAS AUTOPARTE",
(SELECT COALESCE(SUM(CA.PRECIO), 0)/COALESCE(SUM(CA.UNIDADES), 1) FROM BAGUVIX.BI_COMPRAS_AUTOPARTES CA WHERE CA.ID_AUTOPARTE = A.CODIGO) AS "PRECIO PROMEDIO COMPRAS AUTOPARTE"
FROM BAGUVIX.BI_AUTOPARTES A
GO

CREATE VIEW BAGUVIX.BI_GANANCIAS_AUTOPARTES
AS
SELECT 
T.anio AS AÑO,
T.MES, 
S.CODIGO AS "CODIGO DE SUCURSAL" , 
S.MAIL AS "MAIL DE SUCURSAL",
(SELECT COALESCE(SUM(VA.PRECIO), 0) FROM BAGUVIX.BI_VENTAS_AUTOPARTES VA WHERE VA.ID_SUCURSAL = S.CODIGO AND VA.ID_TIEMPO = T.ID_TIEMPO) - (SELECT COALESCE(SUM(CA.PRECIO), 0) FROM BAGUVIX.BI_COMPRAS_AUTOPARTES CA WHERE CA.ID_SUCURSAL = S.CODIGO AND CA.ID_TIEMPO = T.ID_TIEMPO) AS "GANANCIAS"
FROM BAGUVIX.BI_TIEMPO T, BAGUVIX.BI_SUCURSAL S 
GROUP BY T.mes, T.anio, T.id_tiempo, S.MAIL, S.CODIGO
GO

CREATE VIEW BAGUVIX.BI_STOCK_ANUAL_POR_SUCURSAL
AS
SELECT 
T.anio AS AÑO,
S.CODIGO AS "CODIGO DE SUCURSAL" , 
S.MAIL AS "MAIL DE SUCURSAL",
(
SELECT SUM(CA.UNIDADES) 
FROM BAGUVIX.BI_COMPRAS_AUTOPARTES CA 
LEFT JOIN BAGUVIX.BI_TIEMPO T1
ON T1.id_tiempo = CA.ID_TIEMPO
WHERE T1.anio <= T.anio AND CA.ID_SUCURSAL = S.CODIGO
) - (
SELECT SUM(VA.UNIDADES) 
FROM BAGUVIX.BI_VENTAS_AUTOPARTES VA 
LEFT JOIN BAGUVIX.BI_TIEMPO T1
ON T1.id_tiempo = VA.ID_TIEMPO
WHERE T1.anio <= T.anio AND VA.ID_SUCURSAL = S.CODIGO
) AS "STOCK"
FROM BAGUVIX.BI_TIEMPO T, BAGUVIX.BI_SUCURSAL S 
GROUP BY T.anio, S.MAIL, S.CODIGO
GO

COMMIT
